# To change this template, choose Tools | Templates
# and open the template in the editor.

__author__="naved"
__date__ ="$28 Dec, 2010 4:33:13 PM$"

xdomains={
"http://etelecare.taleo.net":["Stream Global Services","http://www.stream.com"],
"http://sunrise.taleo.net":["Sunrise Senior Living ","http://www.sunriseseniorliving.com"],
"http://hess.taleo.net":["Hess","http://www.hess.com"],
"http://revlon.taleo.net":["Revlon ","http://www.revlon.com"],
"http://rac.taleo.net":["Rent-A-Center ","http://www.rentacenter.com"],
"http://pb.taleo.net":["Pitney Bowes","http://www.pb.com"],
"http://cymer.taleo.net":["Cymer ","http://www.cymer.com"],
"http://whirlpool.taleo.net":["Whirlpool ","http://www.whirlpool.com"],
"http://tiaa.taleo.net":["TIAA-CREF Financial Services ","https://www.tiaa-cref.org"],
"http://cdw.taleo.net":["CDW ","http://www.cdw.com/"],
"http://ccservices.taleo.net":["Creative Computer Services","http://www.ccservices.com"],
"http://reedelsevier.taleo.net":["Read Elsevier ","http://www.reed-elsevier.com"],
"http://lyondell.taleo.net":["LyondellBasell","http://www.lyondellbasell.com"],
"http://scotts.taleo.net":["Scotts","http://www.scotts.com"],
"http://wm.taleo.net":["Waste Management ","http://www.wm.com"],
"http://beca.taleo.net":["Beca ","http://www.beca.com"],
"http://merckgroup.taleo.net":["Merck Serono ","http://www.merckserono.com"],
"http://coty.myvurv.taleo.net":["Taleo Acquires Vurv Technology","http://www.vurv.com"],
"http://pdstech.taleo.net":["PDS Tech ","http://www.pdstech.com"],
"http://baesystems.taleo.net":["BAE Systems","http://www.baesystems.com"],
"http://rrienergy.taleo.net":["RRI Energy ","http://www.rrienergy.com"],
"http://ncr.taleo.net":["",""],
"http://armstrong.taleo.net":["Armstrong","http://www.armstrong.com"],
"http://tuvsudap.taleo.net":["TUV SUD ","http://www.tuv-sud.in"],
"http://foschini.taleo.net":["Foschini ","http://www.foschini.co.za"],
"http://allergan.taleo.net":["Allergan ","http://www.allergan.com"],
"http://bms.taleo.net":["British-Myers Squibb ","http://www.bms.com"],
"http://cce.taleo.net":["Coca Cola Enterprises ","http://www.cokecce.com"],
"http://hmshost.taleo.net":["HMS Host ","http://www.hmshost.com"],
"http://wellcare.taleo.net":["WellCare ","http://www.wellcare.com"],
"http://fanniemae.taleo.net":["Fannie Mae ","http://www.fanniemae.com"],
"http://ghd.taleo.net":["GHD ","http://www.ghd.com"],
"http://maximhealth.taleo.net":["Maxim Healthcare Services ","http://www.maximhealthcare.com"],
"http://gmp.taleo.net":["GMP","http://www.gmprecruit.com"],
"http://danaher.taleo.net":["Danaher ","http://www.danaher.com"],
"http://appliedmat.taleo.net":["Applied Materials ","http://www.appliedmaterials.com"],
"http://pacificorp.taleo.net":["PacifiCorp","http://www.pacificorp.com"],
"http://gallup.taleo.net":["Gallup ","http://www.gallup.com"],
"http://hca.taleo.net":["Central Florida Regional Hospital ","http://www.centralfloridaregional.com"],
"http://yellowpages.taleo.net":["Yellow Pages Group ","http://www.ypg.com"],
"http://ashland.taleo.net":["Ashland ","http://www.ashland.com"],
"http://jnj.taleo.net":["Johnson & Johnson ","http://www.jnj.com"],
"http://lpsvcs.taleo.net":["Lender Processing Services ","http://www.lpsvcs.com"],
"http://usbank.taleo.net":["US Bank ","http://www.usbank.com"],
"http://cirquedusoleil.taleo.net":["Cirque Du Soleil ","http://www.cirquedusoleil.com"],
"http://ucb.taleo.net":["UCB ","http://www.ucb.com"],
"http://solutionexchange.taleo.net":["Solution Exchange ","http://solutionexchange.taleo.net"],
"http://bd.taleo.net":["Becton, Dickinson and Company","http://www.bd.com"],
"http://citi.taleo.net":["Citi","http://www.citigroup.com"],
"http://paychex.taleo.net":["Paychex ","http://www.paychex.com"],
"http://roche.taleo.net":["Roche","http://www.roche.com"],
"http://renault.taleo.net":["",""],
"http://target.taleo.net":["",""],
"http://fujitsujobs.taleo.net":["Fujitsu ","http://www.fujitsu.com"],
"http://aci.taleo.net":["",""],
"http://harristeeter.taleo.net":["",""],
"http://merckco.taleo.net":["Merck ","http://www.merck.com"],
"http://genzyme.taleo.net":["Genzyme Genetics","http://www.genzymegenetics.com"],
"http://hyatt.taleo.net":["Hyatt ","http://www.hyatt.com"],
"http://stjohn.taleo.net":["St. John Providence Health System","http://www.stjohnprovidence.org"],
"http://wamu.taleo.net":["",""],
"http://publicstorage.taleo.net":["Public Storage ","http://www.publicstorage.com"],
"http://de.taleo.net":["Duke Energy ","http://www.duke-energy.com"],
"http://allstate.taleo.net":["Allstate ","http://www.allstate.com"],
"http://didata.taleo.net":["Dimension Data ","http://www.dimensiondata.com"],
"http://veritude.taleo.net":["Veritude","http://www.veritude.com"],
"http://starwood.taleo.net":["",""],
"http://csg.taleo.net":["CSG Systems","http://www.csgsystems.com"],
"http://capgemini.taleo.net":["Cap Gemini","http://www.capgemini.com"],
"http://stgintel.taleo.net":["Intel ","http://www.intel.com"],
"http://bqpopulaire.taleo.net":["Banque Populaire ","http://www.banquepopulaire.fr"],
"http://dominos.taleo.net":["Domino's Pizza ","http://www.dominos.com"],
"http://ey.taleo.net":["Ernst & Young ","http://www.ey.com"],
"http://ncogroup.taleo.net":["NCO ","http://www.ncogroup.com"],
"http://stanley.taleo.net":["Stanley Hand Tools","http://www.stanleytools.com"],
"http://alcatelucent.taleo.net":["Alcatel-Lucent ","http://www.alcatel-lucent.com"],
"http://academy.taleo.net":["Academy Sports+Outdoor ","http://www.academy.com"],
"http://purdue.taleo.net":["Indiana University-Purdue University Fort Wayne","http://ipfw.edu"],
"http://aonuk.taleo.net":["AON ","http://www.aon.com"],
"http://bcbst.taleo.net":["BlueCross BlueShield or Tennesse","http://www.bsbst.com"],
"http://ampi.taleo.net":["Conde Nast ","http://www.condenast.com"],
"http://amerch.taleo.net":["Anderson Merchandisers ","http://www.amerch.com"],
"http://weatherford.taleo.net":["Weatherford ","http://www.weatherford.com"],
"http://nordstrom.taleo.net":["Nordstrom ","http://shop.nordstrom.com"],
"http://bmw.taleo.net":["BMW ","http://www.bmw.com"],
"http://equifax.taleo.net":["Equifax ","http://www.equifax.com"],
"http://bnymellon.taleo.net":["BNY Mellon ","http://www.bnymellon.com"],
"http://avanade.taleo.net":["Avanade ","http://www.avanade.com"],
"http://qad.taleo.net":["",""],
"http://faurecia.taleo.net":["Faurecia ","http://www.faurecia.com"],
"http://aramark.taleo.net":["Aramark ","http://www.aramark.com"],
"http://riotinto.taleo.net":["Rio Tinto ","http://www.riotinto.com"],
"http://bombardier.taleo.net":["Bombardier ","http://www.bombardier.com"],
"http://toyota.taleo.net":["Toyota ","http://www.toyota.com"],
"http://freshmarket.taleo.net":["The Fresh Market ","http://www.thefreshmarket.com"],
"http://fnis.taleo.net":["FIS ","http://www.fisglobal.com"],
"http://eaglegl.taleo.net":["Ceva","http://www.cevalogistics.com"],
"http://teachforamerica.taleo.net":["Teach For America ","http://www.teachforamerica.org"],
"http://raymondjames.taleo.net":["Raymond James","http://www.raymondjames.com"],
"http://adobe.taleo.net":["Adobe ","http://www.adobe.com"],
"http://banquenationaleducanada.taleo.net":["Banque Nationale Group Financier ","http://www.bnc.ca"],
"http://asm.taleo.net":["",""],
"http://abitibiconsol.taleo.net":["Abitibi Bowater ","http://www.abitibibowater.com"],
"http://chicago.taleo.net":["City of Chicago ","http://www.cityofchicago.org"],
"http://verisign.taleo.net":["VeriSign ","http://www.verisign.com"],
"http://chi.taleo.net":["Catholic Health Initiatives","http://www.catholichealthinit.org"],
"http://amazon.taleo.net":["",""],
"http://jeffersonwells.taleo.net":["Jefferson Wells ","http://www.jeffersonwells.com"],
"http://takedapharm.taleo.net":["Takeda Pharmaceutical Company Limited ","http://www.takeda.com"],
"http://panerabread.taleo.net":["Panera Bread ","http://www.panerabread.com"],
"http://directv.taleo.net":["DirecTV Satellite Television ","http://www.directv.com"],
"http://cheesecake.taleo.net":["The Cheesecake Factory","http://www.thecheesecakefactory.com"],
"http://tas-ericsson.taleo.net":["Ericsson ","http://www.ericsson.com"],
"http://avon.taleo.net":["AVON ","http://www.avon.com"],
"http://kp.taleo.net":["Kaiser Permanente","https://www.kaiserpermanente.org"],
"http://ppmenergy.taleo.net":["Iberdrola Renewables ","http://www.iberdrolarenewables.us"],
"http://aaronrents.taleo.net":["",""],
"http://areva.taleo.net":["Areva ","http://www.areva.com"],
"http://suntrust.taleo.net":["SunTrust ","https://www.suntrust.com"],
"http://vailresorts.taleo.net":["Vail Resorts","http://www.vailresorts.com"],
"http://panasonic.taleo.net":["Panasonic ","http://www.panasonic.com"],
"http://csaa.taleo.net":["AAA ","http://www.csaa.com"],
"http://pnc.taleo.net":["",""],
"http://csc.taleo.net":["CSC ","http://www.csc.com"],
"http://macys.taleo.net":["Macy's ","http://www.macys.com"],
"http://ual-ao.taleo.net":["United","http://www.united.com"],
"http://abercrombie.taleo.net":["Abercrombie & Fitch ","http://www.abercrombie.com"],
"http://mars.taleo.net":["Mars ","http://www.mars.com"],
"http://sony.taleo.net":["Sony ","http://www.sony.com"],
"http://zionsbancorp.taleo.net":["Zions Bancorporation ","http://www.zionsbancorporation.com"],
"http://hutchison.taleo.net":["",""],
"http://woodforest.taleo.net":["Wood Forest ","http://www.woodforest.com"],
"http://icfi.taleo.net":["ICF International ","http://www.icfi.com"],
"http://embarq.taleo.net":["",""],
"http://ats.taleo.net":["Advanced Technology Services, Inc. ","http://www.advancedtech.com"],
"http://iadbcareers.taleo.net":["Banque Interamericaine de Developpement","http://www.iadb.org"],
"http://wendys.taleo.net":["",""],
"http://honeywell.taleo.net":["Honeywell ","http://www.honeywell.com"],
"http://bcbsmn.taleo.net":["Blue Cross BlueShield of Michigan ","http://www.bcbsm.com"],
"http://garmin.taleo.net":["Garmin ","http://www.garmin.com"],
"http://newasurion.taleo.net":["New ","https://www.newcorp.com"],
"http://iberdrolausa.taleo.net":["Iberdrola Renewables ","http://www.iberdrolarenewables.us"],
"http://uboc.taleo.net":["Union Bank ","https://unionbank.com"],
"http://tenet.taleo.net":["Tenet ","http://www.tenethealth.com"],
"http://amairlines.taleo.net":["American Airlines ","http://www.aa.com"],
"http://dowjones.taleo.net":["Dow Jones ","http://www.dowjones.com"],
"http://baptisthlth.taleo.net":["Baptist Health ","http://www.baptist-health.com"],
"http://ual-pro.taleo.net":["United","http://www.united.com"],
"http://blizzard.taleo.net":["Blizzard Entertainment","http://us.blizzard.com"],
"http://cornellu.taleo.net":["Cornell University ","http://www.cornell.edu"],
"http://toysrus.taleo.net":["Toysrus ","http://www.toysrus.com"],
"http://bankwest.taleo.net":["Bankwest","http://www.bankwest.com.au"],
"http://berlex.taleo.net":["",""],
"http://qantas.taleo.net":["Quantas ","http://www.qantas.com.au"],
"http://barco.taleo.net":["Barco ","http://www.barco.com"],
"http://unum.taleo.net":["Unum ","http://www.unum.com"],
"http://tbe.taleo.net":["",""],
"http://taleo.taleo.net":["Taleo ","http://new.taleo.com"],
"http://frostbank.taleo.net":["Frost ","https://www.frostbank.com"],
"http://teradata.taleo.net":["Teradata ","http://www.teradata.com"],
"http://rgisllc.taleo.net":["RGIS ","http://www.rgis.com"],
"http://davita.taleo.net":["DaVita ","http://www.davita.com"],
"http://grouphealth.taleo.net":["",""],
"http://cop.taleo.net":["ConocoPhillips ","http://www.conocophillips.com"],
"http://levistrauss.taleo.net":["Levi Strauss & Co. ","http://www.levistrauss.com"],
"http://cbc.taleo.net":["CBC Radio-Canada","http://cbc.radio-canada.ca"],
"http://shaw.taleo.net":["",""],
"http://barclays.taleo.net":["Barclays ","http://group.barclays.com"],
"http://mmc.taleo.net":["Marsh and McLennan Companies","http://www.mmc.com"],
"http://burnsmcdonn.taleo.net":["Burns & McDonnell ","http://www.burnsmcd.com"],
"http://kindred.taleo.net":["Kindred Healthcare ","http://www.kindredhealthcare.com"],
"http://gapinc.taleo.net":["Gap Inc. ","http://www.gapinc.com"],
"http://baylor.taleo.net":["Baylor ","http://www.baylor.edu"],
"http://activision.taleo.net":["Activision Blizzard","http://www.activisionblizzard.com"],
"http://intel.taleo.net":["Intel ","http://www.intel.com"],
"http://mmm.taleo.net":["3M ","http://www.3m.com"],
"http://pepsiamericas.taleo.net":["Pepsi Americas ","http://www.pepsiamericas.com"],
"http://kraftfoods.taleo.net":["Kraft Foods ","http://www.kraftfoodscompany.com"],
"http://bcbsm.taleo.net":["Blue Cross BlueShield of Michigan ","http://www.bcbsm.com"],
"http://ciber.taleo.net":["",""],
"http://ams.taleo.net":["",""],
"http://aircanada.taleo.net":["Air Canada ","http://www.aircanada.com"],
"http://uhg.taleo.net":["United Health Group ","http://www.unitedhealthgroup.com"],
"http://tsocorp.taleo.net":["Tesoro Corporation ","http://www.tsocorp.com"],
"http://cargill.taleo.net":["Cargill ","http://www.cargill.com"],
"http://hewitt.taleo.net":["Hewitt ","http://www.hewittassociates.com"],
"http://bam.taleo.net":["Books-A-Million ","http://www.booksamillion.com"],
"http://pg.taleo.net":["Procter & Gamble ","http://www.pg.com"],
"http://fpl.taleo.net":["NextEra Energy ","http://www.nexteraenergy.com"],
"http://troweprice.taleo.net":["",""],
"http://tmobileusa.taleo.net":["T-Mobile ","http://www.t-mobile.com"],
"http://kohls.taleo.net":["Kohl's ","http://www.kohls.com"],
"http://medica.taleo.net":["Medica ","http://www.medica.com"],
"http://eandis.taleo.net":["Eandis ","http://www.eandis.be"],
"http://westpac.taleo.net":["Westpac","http://www.westpac.com.au"],
"http://batesville.taleo.net":["Batesville ","http://www.batesville.com"],
"http://rogers.taleo.net":["Rogers ","http://www.rogers.com"],
"http://assurant.taleo.net":["Assurant ","http://www.assurant.com"],
"http://lifespan.taleo.net":["Lifespan ","http://www.lifespan.org"],
"http://hbosa.taleo.net":["Bankwest ","http://www.bankwest.com.au"],
"http://ihc.taleo.net":["Intermountain Healthcare ","http://intermountainhealthcare.org"],
"http://analog.taleo.net":["Analog Devices ","http://www.analog.com"],
"http://avagotech.taleo.net":["Avago Technologies","http://www.avagotech.com"],
"http://thomascook.taleo.net":["Thomas Cook ","http://www.thomascook.com"],
"http://huskyenergy.taleo.net":["Husky Energy Inc. ","http://www.huskyenergy.ca"],
"http://woolworths.taleo.net":["Woolworths ","http://www.woolworths.com.au"],
"http://bnpparibasus.taleo.net":["",""],
"http://min.taleo.net":["Ministry Health Care ","http://ministryhealth.org"],
"http://merck.taleo.net":["Merck ","http://www.merck.com"],
"http://pr.taleo.net":["Pernod Ricard","http://www.pernod-ricard.com"],
"http://telus.taleo.net":["Telus ","http://telus.com"],
"http://comerica.taleo.net":["Comerica ","http://www.comerica.com"],
"http://amec.myvurv.taleo.net":["Amec ","http://www.amec.com"],
"http://playstation.taleo.net":["PlayStation ","http://us.playstation.com"],
#"http://tsc.taleo.net":["",""],
"http://dsm.taleo.net":["DSM ","http://www.dsm.com"],
"http://toc.taleo.net":["Thomson Reuters ","http://thomsonreuters.com"],
"http://caci.taleo.net":["CACI ","http://www.caci.com"],
"http://adc.taleo.net":["ADC ","http://www.adc.com"],
"http://cardinal.taleo.net":["Cardinal Health ","http://www.cardinal.com"],
"http://fonterra.taleo.net":["Fonterra ","http://www.fonterra.com"],
"http://reliant.taleo.net":["RRI Energy ","http://www.rrienergy.com"],
"http://directenergy.taleo.net":["Direct Energy ","http://www.directenergy.com"],
"http://bmc.taleo.net":["Boston Medical Center ","http://www.bmc.org"],
"http://gopenske.taleo.net":["Penske ","http://www.gopenske.com"],
"http://infoprint.taleo.net":["Ricoh Infoprint Solutions ","http://www.infoprint.com"],
"http://ceb.taleo.net":["Corporate Executive Board ","http://www.executiveboard.com"],
"http://jonesapparel.taleo.net":["Jones Apparel Group ","http://www.jonesapparel.com"],
"http://dnb.taleo.net":["Dun & Bradstreet ","http://www.dnb.com"],
"http://schneider.taleo.net":["",""],
"http://meijer.taleo.net":["Meijer ","http://www.meijer.com"],
"http://dupontimpl.taleo.net":["DU PONT ","http://www.dupont.com"],
"http://booz.taleo.net":["Booz & Co. ","http://www.booz.com"],
"http://yellow.taleo.net":["YRC Logistics ","http://www.yrclogistics.com"],
"http://healthways.taleo.net":["Healthways ","http://www.healthways.com"],
"http://hok.taleo.net":["HOK ","http://www.hok.com"],
"http://uscellular.taleo.net":["U. S. Cellular ","http://www.uscellular.com"],
"http://shrm.taleo.net":["Society for Human Resource Management ","http://www.shrm.org"],
"http://kingfisher.taleo.net":["B & Q ","http://www.diy.com"],
"http://elpaso.taleo.net":["el paso ","http://www.elpaso.com"],
"http://dow.taleo.net":["DOW  ","http://www.dow.com"],
"http://rim.taleo.net":["Rim ","http://www.rim.com"],
"http://ing.taleo.net":["",""],
"http://desjardins.taleo.net":["Desjardins ","http://www.desjardins.com"],
"http://woodsidehiringnow.taleo.net":["Woodside ","http://www.woodside.com.au"],
"http://ihg.taleo.net":["InterContinental Hotels Group ","http://www.ichotelsgroup.com"],
"http://bjc.taleo.net":["BJC HealthCare ","http://www.bjc.org"],
"http://pch.taleo.net":["Phoenix Children's Hospital","http://www.phoenixchildrens.com"],
"http://rsc.taleo.net":["RSC Equipment Rental ","http://www.rscrental.com"],
"http://dessau.taleo.net":["Dessau ","http://www.dessau.com"],
"http://lifetime.taleo.net":["Lifetime Fitness ","http://www.lifetimefitness.com"],
"http://pgecorp.taleo.net":["PG&E Corporation ","http://www.pgecorp.com"],
"http://tatatechnologies.myvurv.taleo.net":["Tata Technologies ","http://www.tatatechnologies.com"],
"http://lifepoint.taleo.net":["LifePoint Hospitals ","http://www.lifepointhospitals.com"],
"http://merckexecutive.taleo.net":["Merck ","http://www.merck.com"],
"http://southerncompany.taleo.net":["Southern Company ","http://www.southerncompany.com"],
"http://imflash.taleo.net":["IM Flash Technologies ","http://www.imftech.com"],
"http://baloise.taleo.net":["Baloise Group ","http://www.baloise.com"],
"http://teletech.taleo.net":["TeleTech ","http://www.teletech.com"],
"http://dell.taleo.net":["",""],
"http://rb.taleo.net":["Reckitt Benckiser Group","http://www.rb.com"],
"http://micron.taleo.net":["Micron ","http://www.micron.com"],
"http://nwl.taleo.net":["Newell Rubbermaid ","http://www.newellrubbermaid.com"],
"http://assessment.taleo.net":["",""],
"http://dhserecruit.taleo.net":["Homeland Security ","http://www.dhs.gov"],
"http://intciti.taleo.net":["Citi ","http://www.citigroup.com"],
"http://johndeere.taleo.net":["John Deere ","http://www.deere.com"],
"http://tp.taleo.net":["Tetra Pak","http://www.tetrapak.com"],
"http://hanson.taleo.net":["Hymix ","http://www.hymix.com"],
"http://pmi.taleo.net":["",""],
"http://visainc.taleo.net":["Visa ","http://www.visa.com"],
"http://newmont.taleo.net":["Newmont ","http://www.newmont.com"],
"http://westernunion.taleo.net":["Western Union ","http://www.westernunion.com"],
"http://nintendo.taleo.net":["Nintendo ","http://www.nintendo.com"],
"http://aac.taleo.net":["",""],
"http://astrazeneca.taleo.net":["Astra Zeneca ","http://www.astrazeneca.com"],
"http://pointp.taleo.net":["Point.P ","http://www.pointp.fr"],
"http://basf.taleo.net":["BASF The Chemical Company ","http://www.basf.com"],
"http://chk.taleo.net":["",""],
"http://pru.taleo.net":["Prudential ","https://www.prudential.com"],
"http://donaldson.taleo.net":["Donaldson ","http://www.donaldson.com"],
"http://transfieldservices.taleo.net":["Transfield Services ","http://www.transfieldservices.com"],
"http://languageline.taleo.net":["Language Line Services ","http://www.languageline.com"],
"http://adhbrac.taleo.net":["Auckland Health Jobs ","http://www.aucklandhealthjobs.com"],
"http://boh.taleo.net":["Bank of Hawaii","https://www.boh.com"],
"http://ondeonalco.taleo.net":["Nalco ","http://www.nalco.com"],
"http://videotron.taleo.net":["Videotron ","http://www.videotron.com"],
"http://nshs.taleo.net":["NSLIJ ","http://www.northshorelij.com"],
"http://airtran.taleo.net":["AirTran ","http://www.airtran.com"],
"http://cendant.taleo.net":["",""],
"http://iasis.taleo.net":["IASIS Healthcare ","http://www.iasishealthcare.com"],
"http://bestbuy.taleo.net":["Best Buy","http://www.bestbuy.com"],
"http://nalco.taleo.net":["Nalco ","http://www.nalco.com"],
"http://dgc.taleo.net":["Dollar General ","http://www.dollargeneral.com"],
"http://familydollar.taleo.net":["Family Dollar ","http://www.familydollar.com"],
"http://accenture.taleo.net":["Accenture ","http://www.accenture.com"],
"http://foxtel.taleo.net":["Foxtel ","http://www.foxtel.com.au"],
"http://borgwarner.taleo.net":["",""],
"http://cintas.taleo.net":["Cintas","http://www.cintas.com"],
"http://rockwellcollins.taleo.net":["Rockwell Collins ","http://www.rockwellcollins.com"],
"http://henryschein.taleo.net":["Henry Schein ","http://www.henryschein.com"],
"http://mcps.taleo.net":["Montgomery County Public Schools ","http://www.montgomeryschoolsmd.org"],
"http://walgreens.taleo.net":["Walgreens ","http://www.walgreens.com"],
"http://mh.taleo.net":["The McGraw Hill Companies ","http://www.mcgraw-hill.com"],
"http://starbucks.taleo.net":["Starbucks Coffee ","http://www.starbucks.com"],
"http://thehartford.taleo.net":["The Hartford ","http://www.thehartford.com"],
"http://hsn.taleo.net":["HSN ","http://www.hsn.com"],
"http://autodesk.taleo.net":["Autodesk ","http://usa.autodesk.com"],
"http://jpmchase.taleo.net":["JPMorgan Chase & Co. ","http://www.jpmorganchase.com"],
"http://mo.taleo.net":["Mutual of Omaha ","http://www.mutualofomaha.com"],
"http://monsanto.taleo.net":["Monsanto ","http://www.monsanto.com"],
"http://parsons.taleo.net":["Parsons ","http://www.parsons.com"],
"http://gm.taleo.net":["General Motors ","http://www.gm.com"],
"http://l3com.taleo.net":["L-3 Communications ","http://www.l-3com.com"],
"http://quintiles.taleo.net":["Quintiles ","http://www.quintiles.com"],
"http://govskpsc.taleo.net":["Government of Saskatchewan ","http://www.gov.sk.ca"],
"http://tas-ey.taleo.net":["Ernst & Young ","http://www.ey.com"],
"http://manulife.taleo.net":["Manulife Financial ","http://www.manulife.com"],
"http://plantronics.taleo.net":["Plantronics ","http://www.plantronics.com"],
"http://ppdi.taleo.net":["PPD ","http://www.ppdi.com"],
"http://weyerhaeuser.taleo.net":["Weyerhaeuser ","http://www.weyerhaeuser.com"],
"http://usfood.taleo.net":["U.S. Foodservice ","http://www.usfoodservice.com"],
"http://nokia.taleo.net":["Nokia ","http://www.nokia.com"],
"http://epco.taleo.net":["Enterprise Products ","http://www.enterpriseproducts.com"],
"http://healthnet.taleo.net":["Health Net ","https://www.healthnet.com"],
"http://ericsson.taleo.net":["Ericsson ","http://www.ericsson.com"],
"http://edmonton.taleo.net":["The City of Edmonton ","http://www.edmonton.ca"],
"http://status.tbe.taleo.net":["",""],
"http://cmhcschl.taleo.net":["Canada Mortgage & Housing Corporation ","https://www.cmhc-schl.gc.ca/en"],
"http://pepsibtl.taleo.net":["Pepsico","http://www.pepsico.com"],
"http://fmi.taleo.net":["",""],
"http://jobsnsw.taleo.net":["Jobs.nsw ","http://www.jobs.nsw.gov.au"],
"http://jazz.taleo.net":["Jazz ","http://www.flyjazz.ca"],
"http://csx.taleo.net":["CSX ","http://www.csx.com "],
"http://fidelity.taleo.net":["Fidelity.com ","https://www.fidelity.com"],
"http://blockbuster.taleo.net":["Blockbuster ","http://www.blockbuster.com"],
"http://hm.myvurv.taleo.net":["H&M ","http://www.hm.com"],
"http://bah.taleo.net":["Booz Allen Hamilton ","http://www.boozallen.com"],
"http://cpchem.taleo.net":["Chevron Phillips ","http://www.cpchem.com"],
"http://bayer.taleo.net":["",""],
"http://swift.taleo.net":["Swift ","http://www.swift.com"],
"http://sutterhealth.taleo.net":["Sutter Health ","http://www.sutterhealth.org"],
"http://bskyb.taleo.net":["Sky ","http://www.sky.com"],
"http://bacfhrs.taleo.net":["",""],
"http://diebold.taleo.net":["Diebold ","http://www.diebold.com"],
"http://xcelenergypraxair.taleo.net":["",""],
"http://wyndham.taleo.net":["Wyndham ","http://www.wyndham.com"],
"http://opg.taleo.net":["Ontario Power Generation","http://www.opg.com"],
"http://johnsoncontrols.taleo.net":["Johnson Controls Inc. ","http://www.johnsoncontrols.com"],
"http://experian.taleo.net":["Experian ","http://www.experian.com"],
"http://alstom.taleo.net":["Alstom ","http://www.alstom.com"],
"http://att.taleo.net":["AT&T ","http://www.att.com"],
"http://itron.taleo.net":["Itron ","http://www.itron.com"],
"http://apria.taleo.net":["Apria Healthcare","http://www.apria.com"],
"http://invensys.taleo.net":["Invensys ","http://www.invensys.com"],
"http://dupont.taleo.net":["",""],
"http://ldschurch.taleo.net":["Church Employment Opportunities ","http://www.lds.org"],
"http://nielsen.taleo.net":["Nielsen ","http://en-us.nielsen.com"],
"http://nov.taleo.net":["",""],
"http://jnjc.taleo.net":["Johnson & Johnson ","http://www.jnj.com"],
"http://tnz.taleo.net":["Telecom ","http://www.telecom.co.nz"],
"http://oakley.taleo.net":["Oakley ","http://www.oakley.com"],
"http://lion.taleo.net":["Lion Nathan ","http://www.lion-nathan.com"],
"http://conway.taleo.net":["Con-way ","http://www.con-way.com"],
"http://tas-accenture.taleo.net":["Accenture ","http://www.accenture.com"],
"http://officemax.taleo.net":["Office Max ","http://www.officemax.com"],
"http://imf.taleo.net":["International Monetary Fund ","http://www.imf.org"],
"http://saralee.taleo.net":["Sara Lee ","http://www.saralee.com"],
"http://stationcas.taleo.net":["Station Casinos ","http://www.stationcasinos.com"],
"http://cp.taleo.net":["Colgate Palmolive ","http://www.colgatepalmolive.com"],
"http://vfc.taleo.net":["VF Corporation ","http://www.vfc.com"],
"http://mosaic.taleo.net":["",""],
"http://carefusion.taleo.net":["Care Fusion ","http://www.carefusion.com"],
"http://ihs.taleo.net":["IHS Inc. ","http://www.ihs.com"],
"http://midamerican.taleo.net":["Mid American Energy Holdings Company ","http://www.midamerican.com"],
"http://westfield.taleo.net":["Westfield ","http://westfield.com"],
"http://suez.taleo.net":["GDF Suez ","http://www.gdfsuez.com"],
"http://chs.taleo.net":["Comprehensive Health Services ","http://www.chsmedical.com"],
"http://sas.taleo.net":["SAS ","http://www.sas.com"],
"http://utoronto.taleo.net":["University of Toronto ","http://www.utoronto.ca"],
"http://nike.taleo.net":["Nike ","http://www.nike.com"],
"http://watercorp.taleo.net":["Water Corporation ","http://www.watercorporation.com.au"],
"http://sabre.taleo.net":["Sabre Holdings ","http://www.sabre.com"],
"http://tmm.taleo.net":["Toyota Talent Link ","http://www.toyota.com/html/talentlink"],
"http://cantire.taleo.net":["Canadian Tire ","http://www.canadiantire.ca"],
"http://rolls-royce.taleo.net":["Rolls Royce ","http://www.rolls-royce.com"],
"http://stgexperian.taleo.net":["Experian ","http://www.experian.com"],
"http://hp.taleo.net":["hp ","http://www.hp.com"],
"http://ppg.taleo.net":["PPG Industries ","http://www.ppg.com"],
"http://axa.taleo.net":["AXA Assistance ","http://www.axa-assistance.us"],
"http://choa.taleo.net":["Children's Healthcare of Atlanta ","http://www.choa.org"],
"http://timken.taleo.net":["Timkin ","http://www.timken.com"],
"http://dotfoods.taleo.net":["Dot Foods ","http://www.dotfoods.com"],
"http://gdfsuez.taleo.net":["GDF Suez ","http://www.gdfsuez.com"],
"http://sunlifefinancial.taleo.net":["Sun Life Financial ","http://www.sunlife.com"],
"http://hds.taleo.net":["Hitachi Data Systems ","http://www.hds.com"],
"http://lmig.taleo.net":["Liberty Mutual ","http://www.libertymutualgroup.com"],
"http://wellpoint.taleo.net":["WellPoint ","http://www.wellpoint.com"],
}
