# To change this template, choose Tools | Templates
# and open the template in the editor.

__author__="naved"
__date__ ="$28 Dec, 2010 4:33:13 PM$"

xdomains={
"http://jobs-zebra.icims.com":["Zebra Technologies","http://www.zebra.com"],
"http://jobs-dunnhumby.icims.com":["Dunhumby","http://www.dunnhumby.com"],
"http://jobs-nuance.icims.com":["Nuance","http://www.nuance.com"],
"http://jobs-btginc.icims.com":["Business Technology Group, Inc,","http://www.btginc.com"],
"http://jobs-entegris.icims.com":["Entegris","http://www.entegris.com"],
"http://jobs-terex.icims.com":["Terex Corporation","http://www.terex.com"],
"http://careers-interpublic.icims.com":["Interpublic Group","http://www.interpublic.com"],
"http://careers-qinetiqna.icims.com":["QinetiQ","http://www.qinetiq.com"],
"http://careers-gilt.icims.com":["Gilt Groupe","http://www.gilt.com"],
"http://jobs-vistaprint.icims.com":["VistaPrint","http://www.vistaprint.com"],
"http://jobs-biopointe.icims.com":["BioPointe","http://www.biopointe.com"],
"http://jobs-chl.icims.com":["Community Healthlink","www.communityhealthlink.org"],
"http://jobs-agilysys.icims.com":["Agilysys, Inc.","http://www.agilysys.com"],
"http://jobs-oxy.icims.com":["Oxy","http://www.oxy.com"],
"http://jobs-vitas.icims.com":["VITAS Innovative Hospice Care","http://www.vitas.com"],
"http://jobs-visionit.icims.com":["VisionIT","http://www.visionitinc.com"],
"http://jobs-mcpc.icims.com":["MCPc Technology Products And Solutions","http://www.mcpc.com"],
"http://jobs-standard.icims.com":["The Standard","http://www.standard.com"],
"http://jobs-gandermountain.icims.com":["Gander Mountain","http://www.gandermountain.com"],
"http://jobs-gables.icims.com":["Gables Residential","http://www.gables.com"],
"http://careers-kronos.icims.com":["Kronos","http://www.kronos.com"],
"http://jobs-verisk.icims.com":["Verisk Analytics ","http://www.verisk.com"],
"http://jobs-orbital.icims.com":["Orbital","http://www.orbital.com"],
"http://jobs-redcgroup.icims.com":["Real Estate Disposition Corporation","http://www.redcgroup.com"],
"http://careers-tribune.icims.com":["Tribune","http://www.tribune.com"],
"http://jobs-comrise.icims.com":["Comrise","http://www.comrise.com/"],
"http://jobs-legrand.icims.com":["Legrand","http://www.legrand.us/ortronics"],
"http://jobs-ecpi.icims.com":["ECPI College of Technology","http://www.ecpi.edu/"],
"http://jobs-lizclaiborne.icims.com":["Liz Claborne","http://lizclaiborneinc.com"],
"http://jobs-isofamily.icims.com":["ISO","http://www.iso.com"],
"http://jobs-hanesbrands.icims.com":["Hanesbrands","http://www.hanesbrands.com"],
"http://useducation-devry.icims.com":["U.S.Education","http://www.useducationcorp.com"],
"http://us-erac.icims.com":["enterprise","http://www.erac.com"],
"http://jobs-fhcsd.icims.com":["Family Health Centers of San Diego","http://www.fhcsd.org"],
"http://jobs-mykotronx.icims.com":["SafeNet","http://www.safenet-inc.com"],
"http://jobs1-tevaneuro.icims.com":["Teva Neuroscience","http://www.tevaneuroscience.com/"],
"http://jobs-inspirepharm.icims.com":["Inspire","http://www.inspirepharm.com"],
"http://careers-ymcachicago.icims.com":["YMCA of Metro Chicago","http://www.ymcachgo.org"],
"http://jobs-continental.icims.com":["Continental Airlines","http://www.continental.com"],
"http://jobs-nypl.icims.com":["New York Public Library","http://www.nypl.org"],
"http://jobs-esurance.icims.com":["Esurance","http://www.esurance.com"],
"http://jobs-laborready.icims.com":["Labor Ready","http://www.laborready.com"],
"http://usjobs-hertz.icims.com":["Hertz","http://www.hertz.com"],
"http://jobs-internationaltruck.icims.com":["Navistar","http://www.navistar.com"],
"http://jobs-riteaid.icims.com":["Rite Aid","http://www.riteaid.com"],
"http://jobs-oclc.icims.com":["Online Computer Library Center","www.oclc.org/"],
"http://oklahoma-bokf.icims.com":["BOK Financial Corporation","http://www.bokf.com"],
"http://jobs-juicycouture.icims.com":["Juicy Couture","http://www.juicycouture.com"],
"http://jobs-wrigley.icims.com":["Wrigley ","http://www.wrigley.com"],
"http://jobs-newbalance.icims.com":["New Balance ","http://www.newbalance.com"],
"http://jobs-ascensionhealthso.icims.com":["Ascension Health","http://www.ascensionhealth.org"],
"http://jobs-argonst.icims.com":["Argon ST","http://www.argonst.com"],
"http://careers-erieinsurance.icims.com":["Erie Insurance","http://www.erieinsurance.com/"],
"http://careers-sage.icims.com":["Sage North America","http://www.sagenorthamerica.com"],
"http://jobs-fedexservices.icims.com":["FedEx","http://www.fedex.com"],
"http://jobs-schafer.icims.com":["Schafer","http://www.schafercorp.com"],
"http://jobs-willamettedental.icims.com":["Willamette Dental","http://www.willamettedental.com"],
"http://jobs-crbard.icims.com":["BRD ","http://careers.crbard.com"],
"http://jobs-dresserrand.icims.com":["Dresser-Rand","https://www.dresser-rand.com"],
"http://jobs-inhouse.icims.com":["iCIMS","http://www.icims.com"],
"http://jobs-salusrehab.icims.com":["LaVie Rehab ","http://www.lavierehab.com"],
"http://jobs-nextgen.icims.com":["NextGen Healthcare","http://www.nextgen.com"],
"http://jobs-ybusasales.icims.com":["Yellowbook","http://corporate.yellowbook.com/"],
"http://jobs-bakertilly.icims.com":["Baker Tilly","http://www.bakertilly.com"],
"http://jobs-carhartt.icims.com":["Carhartt","http://www.carhartt.com/"],
"http://jobs-midland.icims.com":["American Modern Insurance Group ","http://www.amig.com"],
"http://jobs-freshdirect.icims.com":["Fresh Direct","http://www.freshdirect.com"],
"http://jobs-solarworld-usa.icims.com":["SolarWorld","http://www.solarworld-usa.com"],
"http://jobs-capstone.icims.com":["Capstone Corporation","http://www.capstonecorp.com"],
"http://jobs-olympus.icims.com":["Olympus Corporation of the Americas","http://www.olympusamerica.com"],
"http://jobs-align.icims.com":["Align","http://www.align.com/"],
"http://jobs-bannerhealth.icims.com":["Banner Health ","https://www.bannerhealth.com"],
"http://jobs-tollbrothers.icims.com":["Toll Brothers","http://www.tollbrothers.com"],
"http://jobs-akamai.icims.com":["Akamai ","http://www.akamai.com"],
"http://careerconnections-devry.icims.com":["DeVry Inc.","http://www.devryinc.com"],
"http://jobs-moneygram.icims.com":["MoneyGram ","https://www.moneygram.com"],
"http://jobs-henkels.icims.com":["Henkels & McCoy","http://henkels.com/Pages/default.aspx"],
"http://jobs-eharmony.icims.com":["eHarmony ","http://www.eharmony.com"],
"http://jobs-stantec.icims.com":["Stantec ","http://www.stantec.com"],
"http://jobs-costar.icims.com":["CoStar Group ","http://www.costar.com"],
"http://jobs-razorfish.icims.com":["Razorfish ","http://www.razorfish.com"],
"http://jobs-emeritus.icims.com":["Emeritus","http://www.emeritus.com"],
"http://jobs-hersheys.icims.com":["Hershey's","http://www.thehersheycompany.com"],
"http://jobs-tradingtechnologies.icims.com":["Trading Technologies ","http://www.tradingtechnologies.com"],
"http://jobs-selectmedicalcorp.icims.com":["Select Medical Corporation ","http://www.selectmedicalcorp.com"],
"http://jobs-tycoelectronics.icims.com":["Tyco Electronics ","http://www.tycoelectronics.com"],
"http://jobs-qivliq.icims.com":["Quvliq","http://www.qivliq.com"],
"http://jobs-achievementfirst.icims.com":["Achievement First ","http://www.achievementfirst.org"],
"http://jobs-meridium.icims.com":["Meridium ","http://www.meridium.com"],
"http://jobs-asrcfederal.icims.com":["ASRC Federal Holding Company ","http://www.asrcfederal.com/"],
"http://jobs-gaic.icims.com":["Great American Insurance Company ","http://www.greatamericaninsurance.com"],
"http://devryuniversity-devry.icims.com":["Devry University ","http://www.devry.edu"],
"http://jobs-woodcons.icims.com":["Wood Consulting Services, Inc.","http://www.woodcons.com"],
"http://jobs-crengland.icims.com":["C. R. England","www.crengland.com/"],
"http://ross-devry.icims.com":["Ross University ","http://www.rossu.edu"],
"http://jobs1-encana.icims.com":["Encana ","http://www.encana.com"],
"http://careers-cswg.icims.com":["C & S Wholesale Grocers ","https://www.cswg.com"],
"http://marketresearchjobs-harrisinteractive.icims.com":["Harris Interactive","http://www.harrisinteractive.com"],
"http://jobs-alexianbrothershealth.icims.com":["Alexian Brothers Health System ","http://www.alexianbrothershealth.org"],
"http://jobs-secura.icims.com":["Secura Insurance Company ","http://www.secura.net"],
"http://jobs-rovicorp.icims.com":["Rovi ","http://www.rovicorp.com"],
"http://jobs-pilgrimspride.icims.com":["Pilgrims Pride ","http://www.pilgrimspride.com"],
"http://careers-acosta.icims.com":["Acosta ","http://www.acosta.com"],
"http://jobs-avalonbay.icims.com":["Avalonbay Communities, Inc.","http://www.avalonbay.com"],
"http://jobs-quantum.icims.com":["Quantum ","http://www.quantum.com"],
"http://jobs-teamschools.icims.com":["TEAM Charter School","http://teamschools.org"],
"http://jobs-acco.icims.com":["ACCO Brands ","http://www.accobrands.com"],
"http://careers-hrblock.icims.com":["H & R Block ","https://www.hrblock.com"],
"http://jobs-castlemetals.icims.com":["A M Castle & Co.","http://www.amcastle.com"],
"http://us-amazon.icims.com":["Amazon ","http://www.amazon.com"],
"http://jobs-depaul.icims.com":["DePaul University","http://depaul.edu"],
"http://jobs-compuware.icims.com":["Compuware ","http://www.compuware.com"],
"http://jobs-tevapharm.icims.com":["Teva Pharmaceuticals ","http://www.tevausa.com"],
"http://jobs-equinox.icims.com":["Equinox","http://www.equinoxfitness.com"],
"http://jobs-3ecompany.icims.com":["3E Company ","http://3ecompany.com"],
"http://jobs-kennedykrieger.icims.com":["Kennedy Krieger Institute ","http://www.kennedykrieger.org"],
"http://jobs-dealer.icims.com":["Dealer.com","http://www.dealer.com"],
"http://jobs-waggeneredstrom.icims.com":["Waggener Edstrom Worldwide","http://waggeneredstrom.com"],
"http://jobs-trustmark.icims.com":["Trustmark Banking & Financial Solutions","https://www.trustmark.com"],
"http://jobs-mtcsc.icims.com":["MTCSC ","http://www.mtcsc.com"],
"http://jobs-ybusa.icims.com":["Yellowbook","http://corporate.yellowbook.com/"],
"http://jobs-santanderconsumerusa.icims.com":["Santander Consumer ","http://www.santanderconsumerusa.com"],
"http://jobs-tessada.icims.com":["Tessada Associates, Inc. ","http://www.tessada.com"]
}